# Setup
baseurl: /
url: https://elixirschool.com
og_image: https://elixirschool.com/assets/fb_share.jpg
permalink: pretty
default_lang: en
exclude_from_localization: []
locales: ['bg', 'bn', 'cn', 'de', 'en', 'es', 'fr', 'gr', 'id', 'it', 'jp', 'ko', 'my', 'no', 'pl', 'pt', 'ru', 'sk', 'tr', 'uk', 'vi']
# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

gems:
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap
  - kramdown

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'vendor']
assets:
  compress:
    css: sass
    js:  uglifier

sitemap:
  file: '/sitemap.xml'
  include_posts:
    - '/index.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'

elixir:
  version: 1.4.4

erlang:
  OTP: 19
  erts: 8.0.2

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Helpers
empty_array: []
